### ISSUE TITLE
tardiness-tracking

### ISSUE THREAD

**Issue by ZamirJamalov** [ZamirJamalov/tardiness-tracking#1]
- [ ]  Gecikmə səbəblərini araşdırmaq onların səbəblərini tapmaq
- [ ]  Gecikmənin performansa təsirini araşdırmaq
- [ ] Ortalama gecikmə vaxtına görə müəyyən güzəştlərin tətbiqi
- [ ] İllər üzrə gecikmə dinamıkasının ölçülməsi
- [ ] Max gecikmə halların aşkar edilməsi günlər* üzrə
- [ ] Son 1 il ərzində gecikmə sayını müəyyən etmək
- [ ] son 1 ay ərzində gecikməyən işçilərin siyahısını əldə etmək
- [ ] Ortalama gecikmə müddəti ən az olan işçilərin maaşın artırılması və ya əlavə məzuniyyət günlərinin qazanması
- [ ] Təyin edilmiş müddətdən çox davamlı gecikən işçilərlə marifləndirici söhbət 
- [ ]  Gecikmələrin qarşısını almaq üçün görülən tədbirlər

-[ ] Tənbeh tədbirləri
-[ ] Tənbeh dərəcələri
-[ ] Həvəsləndirici tədbirlər

-[ ] 1-ci gecikme  xeberdarliq  her gun 5 deq artiq 2-ci gecikme  izahat , 3-cerime  emek haqqinin 1%  i
